//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordCloud.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordCloud.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Build 的本地化字符串。
        /// </summary>
        internal static string BuildWordsCloud_Content {
            get {
                return ResourceManager.GetString("BuildWordsCloud.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        internal static string CloudBackColorPick_AdvancedTabHeader {
            get {
                return ResourceManager.GetString("CloudBackColorPick.AdvancedTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available Colors 的本地化字符串。
        /// </summary>
        internal static string CloudBackColorPick_AvailableColorsHeader {
            get {
                return ResourceManager.GetString("CloudBackColorPick.AvailableColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Colors 的本地化字符串。
        /// </summary>
        internal static string CloudBackColorPick_RecentColorsHeader {
            get {
                return ResourceManager.GetString("CloudBackColorPick.RecentColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Colors 的本地化字符串。
        /// </summary>
        internal static string CloudBackColorPick_StandardColorsHeader {
            get {
                return ResourceManager.GetString("CloudBackColorPick.StandardColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard 的本地化字符串。
        /// </summary>
        internal static string CloudBackColorPick_StandardTabHeader {
            get {
                return ResourceManager.GetString("CloudBackColorPick.StandardTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word Cloud Background Color 的本地化字符串。
        /// </summary>
        internal static string CloudBackColorPick_ToolTip {
            get {
                return ResourceManager.GetString("CloudBackColorPick.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background: 的本地化字符串。
        /// </summary>
        internal static string CloudBackgroundLabel_Text {
            get {
                return ResourceManager.GetString("CloudBackgroundLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick Background Image 的本地化字符串。
        /// </summary>
        internal static string CloudBackImagePick_ToolTip {
            get {
                return ResourceManager.GetString("CloudBackImagePick.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building ... 的本地化字符串。
        /// </summary>
        internal static string CloudBuildingIndicator_BusyContent {
            get {
                return ResourceManager.GetString("CloudBuildingIndicator.BusyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font: 的本地化字符串。
        /// </summary>
        internal static string CloudFontLabel_Text {
            get {
                return ResourceManager.GetString("CloudFontLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H: 的本地化字符串。
        /// </summary>
        internal static string CloudHeightLabel_Text {
            get {
                return ResourceManager.GetString("CloudHeightLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Margin: 的本地化字符串。
        /// </summary>
        internal static string CloudMarginLabel_Text {
            get {
                return ResourceManager.GetString("CloudMarginLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mask Image: 的本地化字符串。
        /// </summary>
        internal static string CloudMaskImageLabel_Text {
            get {
                return ResourceManager.GetString("CloudMaskImageLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick Mask Image 的本地化字符串。
        /// </summary>
        internal static string CloudMaskImagePick_ToolTip {
            get {
                return ResourceManager.GetString("CloudMaskImagePick.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orientation: 的本地化字符串。
        /// </summary>
        internal static string CloudOrientationLabel_Text {
            get {
                return ResourceManager.GetString("CloudOrientationLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W: 的本地化字符串。
        /// </summary>
        internal static string CloudWidthLabel_Text {
            get {
                return ResourceManager.GetString("CloudWidthLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string SaveWordsCloud_Content {
            get {
                return ResourceManager.GetString("SaveWordsCloud.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word Cloud Generator 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
